# Generated by Django 5.2.5 on 2025-09-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='pergunta',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
